name: Set Up Environment

on: [push]

jobs:
  setup-env:
    runs-on: ubuntu-latest

    env:
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
